-- ============================================================
-- SEED — catalogue d'items + banque de missions
-- ⚠️ FICHIER GÉNÉRÉ par scripts/generate-seed.ts — ne pas éditer à la main.
-- ============================================================

-- 42 items
insert into items (slug, name, slot, rarity, params, unlock_hint) values
  ('beach_hat', 'Beach hat', 'head', 'common', '{"shape":"bucket","color":"#F5E0B7","band":"#FF8C7A"}'::jsonb, 'Standup streak'),
  ('party_hat', 'Party hat', 'head', 'common', '{"shape":"cone","color":"#F6C6D8","dots":"#FFFFFF"}'::jsonb, 'Standup streak'),
  ('beret', 'Beret', 'head', 'common', '{"shape":"beret","color":"#52465E"}'::jsonb, 'Standup streak'),
  ('headphones', 'Headphones', 'head', 'uncommon', '{"shape":"headphones","color":"#7ED6DF","pad":"#52465E"}'::jsonb, '5-day streak'),
  ('propeller_cap', 'Propeller cap', 'head', 'uncommon', '{"shape":"propeller","color":"#C8E6F5","propeller":"#FF8C7A"}'::jsonb, '5-day streak'),
  ('flower_crown', 'Flower crown', 'head', 'rare', '{"shape":"flower_crown","colors":["#F6C6D8","#FFF3CF","#CDEBD3"]}'::jsonb, 'Detectives'' victory'),
  ('golden_crown', 'Golden crown', 'head', 'epic', '{"shape":"crown","color":"#F2C14E","gems":"#FF8C7A"}'::jsonb, 'Seasons-played milestone'),
  ('halo', 'Halo', 'head', 'legendary', '{"shape":"halo","color":"#FFE9A0","glow":true}'::jsonb, '??? (very rare)'),
  ('round_glasses', 'Round glasses', 'face', 'common', '{"shape":"round","color":"#52465E"}'::jsonb, 'Standup streak'),
  ('sunglasses', 'Sunglasses', 'face', 'common', '{"shape":"square","color":"#2F2A38"}'::jsonb, 'Standup streak'),
  ('heart_sunglasses', 'Heart sunglasses', 'face', 'uncommon', '{"shape":"heart","color":"#F2A9A0"}'::jsonb, '5-day streak'),
  ('dive_mask', 'Diving mask', 'face', 'uncommon', '{"shape":"dive","color":"#7ED6DF","strap":"#52465E"}'::jsonb, 'Team victory'),
  ('monocle', 'Monocle', 'face', 'rare', '{"shape":"monocle","color":"#F2C14E"}'::jsonb, 'Detectives'' victory'),
  ('pirate_patch', 'Pirate eye patch', 'face', 'rare', '{"shape":"patch","color":"#2F2A38"}'::jsonb, 'Rabbit victory'),
  ('bow_tie', 'Bow tie', 'neck', 'common', '{"shape":"bow","color":"#FF8C7A"}'::jsonb, 'Standup streak'),
  ('striped_scarf', 'Striped scarf', 'neck', 'common', '{"shape":"scarf","colors":["#C8E6F5","#FFFDF8"]}'::jsonb, 'Standup streak'),
  ('bell_collar', 'Bell collar', 'neck', 'uncommon', '{"shape":"bell","color":"#D9C7F2","bell":"#F2C14E"}'::jsonb, '5-day streak'),
  ('flower_lei', 'Flower lei', 'neck', 'uncommon', '{"shape":"lei","colors":["#F6C6D8","#FFF3CF","#CDEBD3"]}'::jsonb, 'Team victory'),
  ('pearl_necklace', 'Pearl necklace', 'neck', 'rare', '{"shape":"pearls","color":"#FFFDF8"}'::jsonb, 'Detectives'' victory'),
  ('cape', 'Cape', 'neck', 'epic', '{"shape":"cape","color":"#B79BD9","lining":"#FFF3CF"}'::jsonb, 'Seasons-played milestone'),
  ('carrot_classic', 'Classic carrot', 'hand', 'common', '{"shape":"carrot","color":"#FF8C42","leaf":"#7BC47F"}'::jsonb, 'First standup'),
  ('coffee_mug', 'Coffee mug', 'hand', 'common', '{"shape":"mug","color":"#FFFDF8","drink":"#6B4F3A"}'::jsonb, 'Standup streak'),
  ('ice_cream', 'Ice cream', 'hand', 'common', '{"shape":"icecream","scoop":"#F6C6D8","cone":"#EBD8C3"}'::jsonb, 'Standup streak'),
  ('mini_laptop', 'Mini laptop', 'hand', 'uncommon', '{"shape":"laptop","color":"#BFC9D9","screen":"#C8E6F5"}'::jsonb, '5-day streak'),
  ('beach_racket', 'Beach paddle', 'hand', 'uncommon', '{"shape":"racket","color":"#FF8C7A","grip":"#EBD8C3"}'::jsonb, 'Team victory'),
  ('magnifier', 'Detective''s magnifier', 'hand', 'rare', '{"shape":"magnifier","color":"#F2C14E","glass":"#C8E6F5"}'::jsonb, 'Detectives'' victory'),
  ('bubble_wand', 'Bubble wand', 'hand', 'rare', '{"shape":"wand","color":"#D9C7F2","bubbles":"#C8E6F5"}'::jsonb, 'Rabbit victory'),
  ('golden_carrot', 'Golden Carrot', 'hand', 'legendary', '{"shape":"carrot","color":"#F2C14E","leaf":"#FFE9A0","glow":true}'::jsonb, 'Validated referral — for the whole island 🥕✨'),
  ('sparkles', 'Sparkles', 'aura', 'common', '{"kind":"sparkles","color":"#FFF3CF","count":8}'::jsonb, 'Standup streak'),
  ('fireflies', 'Fireflies', 'aura', 'uncommon', '{"kind":"fireflies","color":"#FFE9A0","count":10}'::jsonb, '5-day streak'),
  ('petal_particles', 'Petals', 'aura', 'rare', '{"kind":"petals","color":"#F6C6D8","count":12}'::jsonb, 'Rabbit victory'),
  ('rain_cloud', 'Tiny rain cloud', 'aura', 'rare', '{"kind":"cloud","color":"#BFC9D9","drops":"#7ED6DF"}'::jsonb, '??? (funny)'),
  ('stars', 'Stars', 'aura', 'epic', '{"kind":"stars","color":"#FFE9A0","count":6}'::jsonb, 'Seasons-played milestone'),
  ('rainbow', 'Rainbow', 'aura', 'legendary', '{"kind":"rainbow","colors":["#F2A9A0","#FFE9A0","#CDEBD3","#C8E6F5","#D9C7F2"]}'::jsonb, '??? (very rare)'),
  ('house_garland', 'House garland', 'island', 'common', '{"kind":"garland","colors":["#F6C6D8","#FFF3CF","#C8E6F5"]}'::jsonb, 'Detectives'' victory'),
  ('campfire', 'Campfire', 'island', 'common', '{"kind":"campfire","flame":"#FF8C42","wood":"#6B4F3A"}'::jsonb, '4 seasons played'),
  ('giant_buoy', 'Giant buoy', 'island', 'uncommon', '{"kind":"buoy","colors":["#FF8C7A","#FFFDF8"]}'::jsonb, 'Team victory'),
  ('hammock', 'Hammock', 'island', 'uncommon', '{"kind":"hammock","color":"#CDEBD3"}'::jsonb, '12 seasons played'),
  ('pontoon', 'Pontoon', 'island', 'rare', '{"kind":"pontoon","color":"#EBD8C3"}'::jsonb, '24 seasons played'),
  ('beach_swing', 'Beach swing', 'island', 'rare', '{"kind":"swing","color":"#F5E0B7","rope":"#EBD8C3"}'::jsonb, 'Team victory'),
  ('mini_lighthouse', 'Mini lighthouse', 'island', 'epic', '{"kind":"lighthouse","colors":["#FF8C7A","#FFFDF8"],"light":"#FFE9A0"}'::jsonb, '24 seasons played'),
  ('golden_palm', 'Golden palm', 'island', 'legendary', '{"kind":"golden_palm","color":"#F2C14E"}'::jsonb, 'Validated referral 🥕✨')
on conflict (slug) do update set name = excluded.name, params = excluded.params, unlock_hint = excluded.unlock_hint;

-- 60 missions
insert into missions (slug, tool, difficulty, brief_md, detection, params) values
  ('carrot_react_3', 'slack', 1, 'React with 🥕 in **3 different threads** before Friday. Casually.', 'auto', '{"emoji":"carrot","count":3}'::jsonb),
  ('hands_react_2', 'slack', 1, 'Drop a 🙌 on **2 different colleagues'' messages**. Be generous, not suspicious.', 'auto', '{"emoji":"raised_hands","count":2}'::jsonb),
  ('gif_friday_vibes', 'slack', 1, 'Post a GIF (any one) in a public channel. Just one. Well chosen.', 'honor', '{}'::jsonb),
  ('emoji_in_status', 'slack', 1, 'Put a **vegetable** emoji in your Slack status for at least a day.', 'honor', '{}'::jsonb),
  ('thank_someone', 'slack', 1, 'Publicly thank a colleague for something specific. Sincerity is your cover.', 'honor', '{}'::jsonb),
  ('purple_heart_2', 'slack', 1, 'Leave a 💜 on **2 messages** from different people.', 'auto', '{"emoji":"purple_heart","count":2}'::jsonb),
  ('ask_question_channel', 'slack', 1, 'Ask a real question in a channel you haven''t posted in this week.', 'honor', '{}'::jsonb),
  ('morning_greeting', 'slack', 1, 'Wish the team a good day one morning, with a sun emoji. Natural.', 'honor', '{}'::jsonb),
  ('word_constellation', 'slack', 2, 'Slip the word **“constellation”** into a real Slack conversation. Without it seeming weird.', 'auto', '{"word":"constellation"}'::jsonb),
  ('word_phare', 'slack', 2, 'Drop the word **“lighthouse”** into a public channel message. Credible context required.', 'auto', '{"word":"lighthouse"}'::jsonb),
  ('word_boussole', 'slack', 2, 'Use the word **“compass”** in a team discussion. Smoothly.', 'auto', '{"word":"compass"}'::jsonb),
  ('word_marmotte', 'slack', 2, 'Place **“groundhog”** in a conversation. Yes, it''s hard. That''s the game.', 'auto', '{"word":"groundhog"}'::jsonb),
  ('three_threads_replies', 'slack', 2, 'Reply in **3 different threads** you didn''t start, on the same day.', 'auto', '{"count":3,"kind":"thread_reply"}'::jsonb),
  ('compliment_chain', 'slack', 2, 'Compliment the work of **2 colleagues** in 2 different channels, on the same day.', 'honor', '{}'::jsonb),
  ('share_useful_link', 'slack', 2, 'Share a genuinely useful link with the team (article, tool, doc), with a line of context.', 'honor', '{}'::jsonb),
  ('poll_lunch', 'slack', 2, 'Run a light mini-poll in the team channel (lunch, coffee, playlist…). Get at least 2 people to vote.', 'honor', '{}'::jsonb),
  ('emoji_streak_day', 'slack', 2, 'Drop **5 🥕 reactions** during the week, spread across at least 2 days.', 'auto', '{"emoji":"carrot","count":5}'::jsonb),
  ('revive_old_thread', 'slack', 2, 'Usefully revive a thread older than 3 days (a real revival, not a “bump”).', 'honor', '{}'::jsonb),
  ('word_perissodactyle', 'slack', 3, 'Place the word **“perissodactyl”** in a real conversation. Good luck, agent.', 'auto', '{"word":"perissodactyl"}'::jsonb),
  ('word_crepuscule_x2', 'slack', 3, 'Use **“twilight”** in **2 separate messages**, at least a day apart.', 'auto', '{"word":"twilight","count":2}'::jsonb),
  ('haiku_hidden', 'slack', 3, 'Write a message that is secretly a **haiku** (5-7-5). No one should notice before Friday.', 'honor', '{}'::jsonb),
  ('alphabet_message', 'slack', 3, 'Post a useful message whose **first 3 sentences start with A, B, C** in order.', 'honor', '{}'::jsonb),
  ('five_reactions_one_message', 'slack', 3, 'Get **5 reactions** (from 5 people) on a single one of your messages. Without asking.', 'honor', '{}'::jsonb),
  ('start_thread_10_replies', 'slack', 3, 'Start a conversation that reaches **10 replies**. Topic is free, talent is mandatory.', 'honor', '{}'::jsonb),
  ('notion_emoji_page', 'notion', 1, 'Change the icon of a Notion page you own to an **animal** emoji.', 'honor', '{}'::jsonb),
  ('notion_tidy_one', 'notion', 1, 'Tidy or cleanly rename **one** badly-titled Notion page. Quiet housekeeping is your art.', 'honor', '{}'::jsonb),
  ('notion_comment_nice', 'notion', 1, 'Leave a constructive comment on a colleague''s Notion page.', 'honor', '{}'::jsonb),
  ('notion_add_cover', 'notion', 1, 'Add a cover image to a page that doesn''t have one.', 'honor', '{}'::jsonb),
  ('notion_new_page', 'notion', 2, 'Create and publish a **new, useful Notion page** (notes, doc, process) this week.', 'auto', '{"kind":"page_created"}'::jsonb),
  ('notion_word_lagon', 'notion', 2, 'Slip the word **“lagoon”** into a Notion page or comment.', 'honor', '{"word":"lagoon"}'::jsonb),
  ('notion_checklist', 'notion', 2, 'Turn a messy paragraph (yours, or with consent) into a clean **checklist**.', 'honor', '{}'::jsonb),
  ('notion_template', 'notion', 2, 'Create a small reusable **template** for the team (meeting, report, etc.).', 'honor', '{}'::jsonb),
  ('notion_link_pages', 'notion', 2, 'Link **2 existing** Notion pages together with @page mentions. The web is woven.', 'honor', '{}'::jsonb),
  ('notion_glossary', 'notion', 3, 'Create a mini **glossary** (≥5 terms) of the team''s jargon. Someone must read it before Friday.', 'honor', '{}'::jsonb),
  ('notion_archive_sweep', 'notion', 3, 'Archive or merge **3 obsolete pages** (with consent if needed). The ghost''s big cleanup.', 'honor', '{}'::jsonb),
  ('notion_faq', 'notion', 3, 'Start a team **FAQ** with at least 3 real questions and answers.', 'honor', '{}'::jsonb),
  ('kanban_emoji_title', 'kanban', 1, 'Add a relevant emoji to the title of **one ticket** you own.', 'honor', '{}'::jsonb),
  ('kanban_clean_one', 'kanban', 1, 'Fill in the description of an empty ticket (yours). The detectives won''t see a thing.', 'honor', '{}'::jsonb),
  ('kanban_label_garden', 'kanban', 1, 'Add or fix the **labels** on 2 tickets. Board gardening.', 'honor', '{}'::jsonb),
  ('kanban_close_ticket', 'kanban', 2, 'Close **one ticket** this week (a real one, not a ticket made for the occasion).', 'auto', '{"kind":"issue_completed"}'::jsonb),
  ('kanban_split_ticket', 'kanban', 2, 'Split a big ticket into **2 clear subtasks**.', 'honor', '{}'::jsonb),
  ('kanban_estimate_sweep', 'kanban', 2, 'Estimate or re-estimate **3 tickets** in the backlog. No one the wiser.', 'honor', '{}'::jsonb),
  ('kanban_word_iceberg', 'kanban', 2, 'Place the word **“iceberg”** in a ticket description or comment.', 'honor', '{"word":"iceberg"}'::jsonb),
  ('kanban_two_closed', 'kanban', 3, 'Close **2 tickets** this week. The most productive Rabbit in the West.', 'auto', '{"kind":"issue_completed","count":2}'::jsonb),
  ('kanban_zombie_hunt', 'kanban', 3, 'Identify **3 zombie tickets** (>30 days with no activity) and propose their fate in a comment.', 'honor', '{}'::jsonb),
  ('any_compliment_tool', 'any', 1, 'Say something nice (sincerely) about a team tool in a conversation. Any tool.', 'honor', '{}'::jsonb),
  ('any_tea_coffee', 'any', 1, 'Offer a virtual or real coffee/tea to a colleague you rarely talk to.', 'honor', '{}'::jsonb),
  ('any_doc_typo', 'any', 1, 'Fix a typo somewhere (doc, ticket, wiki). The masked proofreader strikes again.', 'honor', '{}'::jsonb),
  ('any_share_win', 'any', 1, 'Share a small win of the week (yours, or a colleague''s with their consent).', 'honor', '{}'::jsonb),
  ('any_meeting_idea', 'any', 2, 'Propose **one concrete idea** in a meeting or in writing this week. Something actionable.', 'honor', '{}'::jsonb),
  ('any_help_unasked', 'any', 2, 'Help a colleague on something **without them asking** (review, proofread, troubleshooting).', 'honor', '{}'::jsonb),
  ('any_teach_trick', 'any', 2, 'Teach someone a trick (shortcut, command, tool). Knowledge spreads.', 'honor', '{}'::jsonb),
  ('any_two_tools_word', 'any', 2, 'Place the word **“archipelago”** in **2 different tools** (Slack + Notion, Slack + ticket…).', 'honor', '{"word":"archipelago"}'::jsonb),
  ('any_intro_two_people', 'any', 2, 'Connect 2 colleagues who should talk about a specific topic.', 'honor', '{}'::jsonb),
  ('any_mini_demo', 'any', 3, 'Give a **mini-demo** (≤5 min) of something you made, to at least 2 people.', 'honor', '{}'::jsonb),
  ('any_process_fix', 'any', 3, 'Spot a small process annoyance and **propose a fix** in writing. Rabbit diplomacy.', 'honor', '{}'::jsonb),
  ('any_silent_week_goal', 'any', 3, 'Set yourself a secret goal Monday, hold it all week, and reveal it Friday after the vote.', 'honor', '{}'::jsonb),
  ('any_three_kindness', 'any', 3, 'Do **3 discreet kind acts** (on 3 different days). If you''re spotted, it doesn''t count.', 'honor', '{"count":3}'::jsonb),
  ('any_lunch_organizer', 'any', 3, 'Organize a team moment (lunch, break, game) that ≥3 people join.', 'honor', '{}'::jsonb),
  ('any_doc_rescue', 'any', 3, 'Find an important piece of info that''s documented nowhere and **document it** cleanly.', 'honor', '{}'::jsonb)
on conflict (slug) do update set brief_md = excluded.brief_md, params = excluded.params;
