-- ============================================================
-- SEED — catalogue d'items + banque de missions
-- ⚠️ FICHIER GÉNÉRÉ par scripts/generate-seed.ts — ne pas éditer à la main.
-- ============================================================

-- 42 items
insert into items (slug, name, slot, rarity, params, unlock_hint) values
  ('beach_hat', 'Bob de plage', 'head', 'common', '{"shape":"bucket","color":"#F5E0B7","band":"#FF8C7A"}'::jsonb, 'Streak de standups'),
  ('party_hat', 'Chapeau de fête', 'head', 'common', '{"shape":"cone","color":"#F6C6D8","dots":"#FFFFFF"}'::jsonb, 'Streak de standups'),
  ('beret', 'Béret', 'head', 'common', '{"shape":"beret","color":"#52465E"}'::jsonb, 'Streak de standups'),
  ('headphones', 'Casque audio', 'head', 'uncommon', '{"shape":"headphones","color":"#7ED6DF","pad":"#52465E"}'::jsonb, 'Streak de 5 jours'),
  ('propeller_cap', 'Casquette à hélice', 'head', 'uncommon', '{"shape":"propeller","color":"#C8E6F5","propeller":"#FF8C7A"}'::jsonb, 'Streak de 5 jours'),
  ('flower_crown', 'Couronne de fleurs', 'head', 'rare', '{"shape":"flower_crown","colors":["#F6C6D8","#FFF3CF","#CDEBD3"]}'::jsonb, 'Victoire des Détectives'),
  ('golden_crown', 'Couronne dorée', 'head', 'epic', '{"shape":"crown","color":"#F2C14E","gems":"#FF8C7A"}'::jsonb, 'Palier de saisons jouées'),
  ('halo', 'Halo', 'head', 'legendary', '{"shape":"halo","color":"#FFE9A0","glow":true}'::jsonb, '??? (très rare)'),
  ('round_glasses', 'Lunettes rondes', 'face', 'common', '{"shape":"round","color":"#52465E"}'::jsonb, 'Streak de standups'),
  ('sunglasses', 'Lunettes de soleil', 'face', 'common', '{"shape":"square","color":"#2F2A38"}'::jsonb, 'Streak de standups'),
  ('heart_sunglasses', 'Lunettes cœur', 'face', 'uncommon', '{"shape":"heart","color":"#F2A9A0"}'::jsonb, 'Streak de 5 jours'),
  ('dive_mask', 'Masque de plongée', 'face', 'uncommon', '{"shape":"dive","color":"#7ED6DF","strap":"#52465E"}'::jsonb, 'Victoire d''équipe'),
  ('monocle', 'Monocle', 'face', 'rare', '{"shape":"monocle","color":"#F2C14E"}'::jsonb, 'Victoire des Détectives'),
  ('pirate_patch', 'Cache-œil de pirate', 'face', 'rare', '{"shape":"patch","color":"#2F2A38"}'::jsonb, 'Victoire du Lapin'),
  ('bow_tie', 'Nœud papillon', 'neck', 'common', '{"shape":"bow","color":"#FF8C7A"}'::jsonb, 'Streak de standups'),
  ('striped_scarf', 'Écharpe rayée', 'neck', 'common', '{"shape":"scarf","colors":["#C8E6F5","#FFFDF8"]}'::jsonb, 'Streak de standups'),
  ('bell_collar', 'Collier à clochette', 'neck', 'uncommon', '{"shape":"bell","color":"#D9C7F2","bell":"#F2C14E"}'::jsonb, 'Streak de 5 jours'),
  ('flower_lei', 'Collier de fleurs', 'neck', 'uncommon', '{"shape":"lei","colors":["#F6C6D8","#FFF3CF","#CDEBD3"]}'::jsonb, 'Victoire d''équipe'),
  ('pearl_necklace', 'Collier de perles', 'neck', 'rare', '{"shape":"pearls","color":"#FFFDF8"}'::jsonb, 'Victoire des Détectives'),
  ('cape', 'Cape', 'neck', 'epic', '{"shape":"cape","color":"#B79BD9","lining":"#FFF3CF"}'::jsonb, 'Palier de saisons jouées'),
  ('carrot_classic', 'Carotte classique', 'hand', 'common', '{"shape":"carrot","color":"#FF8C42","leaf":"#7BC47F"}'::jsonb, 'Premier standup'),
  ('coffee_mug', 'Tasse de café', 'hand', 'common', '{"shape":"mug","color":"#FFFDF8","drink":"#6B4F3A"}'::jsonb, 'Streak de standups'),
  ('ice_cream', 'Glace', 'hand', 'common', '{"shape":"icecream","scoop":"#F6C6D8","cone":"#EBD8C3"}'::jsonb, 'Streak de standups'),
  ('mini_laptop', 'Ordinateur mini', 'hand', 'uncommon', '{"shape":"laptop","color":"#BFC9D9","screen":"#C8E6F5"}'::jsonb, 'Streak de 5 jours'),
  ('beach_racket', 'Raquette de plage', 'hand', 'uncommon', '{"shape":"racket","color":"#FF8C7A","grip":"#EBD8C3"}'::jsonb, 'Victoire d''équipe'),
  ('magnifier', 'Loupe de détective', 'hand', 'rare', '{"shape":"magnifier","color":"#F2C14E","glass":"#C8E6F5"}'::jsonb, 'Victoire des Détectives'),
  ('bubble_wand', 'Baguette à bulles', 'hand', 'rare', '{"shape":"wand","color":"#D9C7F2","bubbles":"#C8E6F5"}'::jsonb, 'Victoire du Lapin'),
  ('golden_carrot', 'Carotte Dorée', 'hand', 'legendary', '{"shape":"carrot","color":"#F2C14E","leaf":"#FFE9A0","glow":true}'::jsonb, 'Parrainage validé — pour toute l''île 🥕✨'),
  ('sparkles', 'Étincelles', 'aura', 'common', '{"kind":"sparkles","color":"#FFF3CF","count":8}'::jsonb, 'Streak de standups'),
  ('fireflies', 'Lucioles', 'aura', 'uncommon', '{"kind":"fireflies","color":"#FFE9A0","count":10}'::jsonb, 'Streak de 5 jours'),
  ('petal_particles', 'Pétales', 'aura', 'rare', '{"kind":"petals","color":"#F6C6D8","count":12}'::jsonb, 'Victoire du Lapin'),
  ('rain_cloud', 'Petit nuage pluvieux', 'aura', 'rare', '{"kind":"cloud","color":"#BFC9D9","drops":"#7ED6DF"}'::jsonb, '??? comique'),
  ('stars', 'Étoiles', 'aura', 'epic', '{"kind":"stars","color":"#FFE9A0","count":6}'::jsonb, 'Palier de saisons jouées'),
  ('rainbow', 'Arc-en-ciel', 'aura', 'legendary', '{"kind":"rainbow","colors":["#F2A9A0","#FFE9A0","#CDEBD3","#C8E6F5","#D9C7F2"]}'::jsonb, '??? (très rare)'),
  ('house_garland', 'Guirlande sur la maison', 'island', 'common', '{"kind":"garland","colors":["#F6C6D8","#FFF3CF","#C8E6F5"]}'::jsonb, 'Victoire des Détectives'),
  ('campfire', 'Feu de camp', 'island', 'common', '{"kind":"campfire","flame":"#FF8C42","wood":"#6B4F3A"}'::jsonb, '4 saisons jouées'),
  ('giant_buoy', 'Bouée géante', 'island', 'uncommon', '{"kind":"buoy","colors":["#FF8C7A","#FFFDF8"]}'::jsonb, 'Victoire d''équipe'),
  ('hammock', 'Hamac', 'island', 'uncommon', '{"kind":"hammock","color":"#CDEBD3"}'::jsonb, '12 saisons jouées'),
  ('pontoon', 'Ponton', 'island', 'rare', '{"kind":"pontoon","color":"#EBD8C3"}'::jsonb, '24 saisons jouées'),
  ('beach_swing', 'Balançoire de plage', 'island', 'rare', '{"kind":"swing","color":"#F5E0B7","rope":"#EBD8C3"}'::jsonb, 'Victoire d''équipe'),
  ('mini_lighthouse', 'Phare miniature', 'island', 'epic', '{"kind":"lighthouse","colors":["#FF8C7A","#FFFDF8"],"light":"#FFE9A0"}'::jsonb, '24 saisons jouées'),
  ('golden_palm', 'Palmier doré', 'island', 'legendary', '{"kind":"golden_palm","color":"#F2C14E"}'::jsonb, 'Parrainage validé 🥕✨')
on conflict (slug) do update set name = excluded.name, params = excluded.params, unlock_hint = excluded.unlock_hint;

-- 60 missions
insert into missions (slug, tool, difficulty, brief_md, detection, params) values
  ('carrot_react_3', 'slack', 1, 'Réagis avec 🥕 dans **3 threads différents** avant vendredi. L''air de rien.', 'auto', '{"emoji":"carrot","count":3}'::jsonb),
  ('hands_react_2', 'slack', 1, 'Pose un 🙌 sur **2 messages de collègues différents**. Sois généreux, pas suspect.', 'auto', '{"emoji":"raised_hands","count":2}'::jsonb),
  ('gif_friday_vibes', 'slack', 1, 'Poste un GIF (n''importe lequel) dans un canal public. Un seul. Bien choisi.', 'honor', '{}'::jsonb),
  ('emoji_in_status', 'slack', 1, 'Mets un emoji **légume** dans ton statut Slack pendant au moins une journée.', 'honor', '{}'::jsonb),
  ('thank_someone', 'slack', 1, 'Remercie publiquement un collègue pour quelque chose de précis. La sincérité est ta couverture.', 'honor', '{}'::jsonb),
  ('purple_heart_2', 'slack', 1, 'Dépose un 💜 sur **2 messages** de personnes différentes.', 'auto', '{"emoji":"purple_heart","count":2}'::jsonb),
  ('ask_question_channel', 'slack', 1, 'Pose une vraie question dans un canal où tu n''as rien posté cette semaine.', 'honor', '{}'::jsonb),
  ('morning_greeting', 'slack', 1, 'Souhaite une bonne journée à l''équipe un matin, avec un emoji soleil. Naturel.', 'honor', '{}'::jsonb),
  ('word_constellation', 'slack', 2, 'Place le mot **« constellation »** dans une vraie conversation Slack. Sans que ça paraisse bizarre.', 'auto', '{"word":"constellation"}'::jsonb),
  ('word_phare', 'slack', 2, 'Glisse le mot **« phare »** dans un message de canal public. Contexte crédible exigé.', 'auto', '{"word":"phare"}'::jsonb),
  ('word_boussole', 'slack', 2, 'Utilise le mot **« boussole »** dans une discussion d''équipe. En douceur.', 'auto', '{"word":"boussole"}'::jsonb),
  ('word_marmotte', 'slack', 2, 'Place **« marmotte »** dans une conversation. Oui, c''est dur. C''est le jeu.', 'auto', '{"word":"marmotte"}'::jsonb),
  ('three_threads_replies', 'slack', 2, 'Réponds dans **3 threads différents** que tu n''as pas démarrés, le même jour.', 'auto', '{"count":3,"kind":"thread_reply"}'::jsonb),
  ('compliment_chain', 'slack', 2, 'Complimente le travail de **2 collègues** dans 2 canaux différents, le même jour.', 'honor', '{}'::jsonb),
  ('share_useful_link', 'slack', 2, 'Partage un lien réellement utile à l''équipe (article, outil, doc), avec une phrase de contexte.', 'honor', '{}'::jsonb),
  ('poll_lunch', 'slack', 2, 'Lance un mini-sondage léger dans le canal d''équipe (déjeuner, café, playlist…). Fais voter au moins 2 personnes.', 'honor', '{}'::jsonb),
  ('emoji_streak_day', 'slack', 2, 'Pose **5 réactions 🥕** dans la semaine, réparties sur au moins 2 jours.', 'auto', '{"emoji":"carrot","count":5}'::jsonb),
  ('revive_old_thread', 'slack', 2, 'Relance utilement un thread vieux de plus de 3 jours (une vraie relance, pas un « up »).', 'honor', '{}'::jsonb),
  ('word_perissodactyle', 'slack', 3, 'Place le mot **« périssodactyle »** dans une vraie conversation. Bonne chance, agent.', 'auto', '{"word":"périssodactyle"}'::jsonb),
  ('word_crepuscule_x2', 'slack', 3, 'Utilise **« crépuscule »** dans **2 messages distincts**, à au moins un jour d''écart.', 'auto', '{"word":"crépuscule","count":2}'::jsonb),
  ('haiku_hidden', 'slack', 3, 'Écris un message qui est secrètement un **haïku** (5-7-5). Personne ne doit le remarquer avant vendredi.', 'honor', '{}'::jsonb),
  ('alphabet_message', 'slack', 3, 'Poste un message utile dont les **3 premières phrases commencent par A, B, C** dans l''ordre.', 'honor', '{}'::jsonb),
  ('five_reactions_one_message', 'slack', 3, 'Obtiens **5 réactions** (de 5 personnes) sur un seul de tes messages. Sans demander.', 'honor', '{}'::jsonb),
  ('start_thread_10_replies', 'slack', 3, 'Démarre une conversation qui atteint **10 réponses**. Le sujet est libre, le talent obligatoire.', 'honor', '{}'::jsonb),
  ('notion_emoji_page', 'notion', 1, 'Change l''icône d''une page Notion que tu possèdes pour un emoji **animal**.', 'honor', '{}'::jsonb),
  ('notion_tidy_one', 'notion', 1, 'Range ou renomme proprement **une page** Notion mal titrée. Le ménage discret, c''est ton art.', 'honor', '{}'::jsonb),
  ('notion_comment_nice', 'notion', 1, 'Laisse un commentaire constructif sur la page Notion d''un collègue.', 'honor', '{}'::jsonb),
  ('notion_add_cover', 'notion', 1, 'Ajoute une cover (image de couverture) à une page qui n''en a pas.', 'honor', '{}'::jsonb),
  ('notion_new_page', 'notion', 2, 'Crée et publie une **nouvelle page Notion** utile (notes, doc, process) cette semaine.', 'auto', '{"kind":"page_created"}'::jsonb),
  ('notion_word_lagon', 'notion', 2, 'Glisse le mot **« lagon »** dans une page ou un commentaire Notion.', 'honor', '{"word":"lagon"}'::jsonb),
  ('notion_checklist', 'notion', 2, 'Transforme un paragraphe fouillis (le tien ou avec accord) en **checklist** propre.', 'honor', '{}'::jsonb),
  ('notion_template', 'notion', 2, 'Crée un petit **template** réutilisable pour l''équipe (réunion, compte-rendu, etc.).', 'honor', '{}'::jsonb),
  ('notion_link_pages', 'notion', 2, 'Relie **2 pages** Notion existantes entre elles avec des mentions @page. La toile se tisse.', 'honor', '{}'::jsonb),
  ('notion_glossary', 'notion', 3, 'Crée un mini **glossaire** (≥5 termes) du jargon de l''équipe. Quelqu''un doit le consulter avant vendredi.', 'honor', '{}'::jsonb),
  ('notion_archive_sweep', 'notion', 3, 'Archive ou regroupe **3 pages obsolètes** (avec accord si besoin). Le grand ménage du fantôme.', 'honor', '{}'::jsonb),
  ('notion_faq', 'notion', 3, 'Démarre une **FAQ d''équipe** avec au moins 3 vraies questions/réponses.', 'honor', '{}'::jsonb),
  ('kanban_emoji_title', 'kanban', 1, 'Ajoute un emoji pertinent au titre d''**un ticket** que tu possèdes.', 'honor', '{}'::jsonb),
  ('kanban_clean_one', 'kanban', 1, 'Complète la description d''un ticket vide (le tien). Les détectives n''y verront que du feu.', 'honor', '{}'::jsonb),
  ('kanban_label_garden', 'kanban', 1, 'Ajoute ou corrige les **labels** de 2 tickets. Jardinage de board.', 'honor', '{}'::jsonb),
  ('kanban_close_ticket', 'kanban', 2, 'Termine **un ticket** cette semaine (un vrai, pas un ticket créé pour l''occasion).', 'auto', '{"kind":"issue_completed"}'::jsonb),
  ('kanban_split_ticket', 'kanban', 2, 'Découpe un gros ticket en **2 sous-tâches** claires.', 'honor', '{}'::jsonb),
  ('kanban_estimate_sweep', 'kanban', 2, 'Estime ou ré-estime **3 tickets** du backlog. Ni vu ni connu.', 'honor', '{}'::jsonb),
  ('kanban_word_iceberg', 'kanban', 2, 'Place le mot **« iceberg »** dans la description ou un commentaire d''un ticket.', 'honor', '{"word":"iceberg"}'::jsonb),
  ('kanban_two_closed', 'kanban', 3, 'Termine **2 tickets** cette semaine. Le Lapin le plus productif de l''Ouest.', 'auto', '{"kind":"issue_completed","count":2}'::jsonb),
  ('kanban_zombie_hunt', 'kanban', 3, 'Identifie **3 tickets zombies** (>30 jours sans activité) et propose leur sort dans un commentaire.', 'honor', '{}'::jsonb),
  ('any_compliment_tool', 'any', 1, 'Dis du bien d''un outil de l''équipe (sincèrement) dans une conversation. N''importe lequel.', 'honor', '{}'::jsonb),
  ('any_tea_coffee', 'any', 1, 'Propose un café/thé virtuel ou réel à un collègue avec qui tu parles peu.', 'honor', '{}'::jsonb),
  ('any_doc_typo', 'any', 1, 'Corrige une coquille quelque part (doc, ticket, wiki). Le correcteur masqué frappe encore.', 'honor', '{}'::jsonb),
  ('any_share_win', 'any', 1, 'Partage une petite victoire de la semaine (la tienne ou celle d''un collègue, avec son accord).', 'honor', '{}'::jsonb),
  ('any_meeting_idea', 'any', 2, 'Propose **une idée concrète** en réunion ou par écrit cette semaine. Quelque chose d''actionnable.', 'honor', '{}'::jsonb),
  ('any_help_unasked', 'any', 2, 'Aide un collègue sur un sujet **sans qu''il l''ait demandé** (revue, relecture, dépannage).', 'honor', '{}'::jsonb),
  ('any_teach_trick', 'any', 2, 'Apprends une astuce (raccourci, commande, outil) à quelqu''un. Le savoir se propage.', 'honor', '{}'::jsonb),
  ('any_two_tools_word', 'any', 2, 'Place le mot **« archipel »** dans **2 outils différents** (Slack + Notion, Slack + ticket…).', 'honor', '{"word":"archipel"}'::jsonb),
  ('any_intro_two_people', 'any', 2, 'Mets en relation 2 collègues qui devraient se parler sur un sujet précis.', 'honor', '{}'::jsonb),
  ('any_mini_demo', 'any', 3, 'Fais une **mini-démo** (≤5 min) de quelque chose que tu as fait, à au moins 2 personnes.', 'honor', '{}'::jsonb),
  ('any_process_fix', 'any', 3, 'Identifie un petit irritant de process et **propose un correctif** par écrit. Diplomatie de lapin.', 'honor', '{}'::jsonb),
  ('any_silent_week_goal', 'any', 3, 'Fixe-toi un objectif secret lundi, tiens-le toute la semaine, et révèle-le vendredi après le vote.', 'honor', '{}'::jsonb),
  ('any_three_kindness', 'any', 3, 'Accomplis **3 gentillesses discrètes** (3 jours différents). Si on te repère, c''est raté.', 'honor', '{"count":3}'::jsonb),
  ('any_lunch_organizer', 'any', 3, 'Organise un moment d''équipe (déjeuner, pause, jeu) auquel ≥3 personnes participent.', 'honor', '{}'::jsonb),
  ('any_doc_rescue', 'any', 3, 'Trouve une info importante qui n''est documentée nulle part et **documente-la** proprement.', 'honor', '{}'::jsonb)
on conflict (slug) do update set brief_md = excluded.brief_md, params = excluded.params;
